# Stack Overflow Developer Survey Analysis

This notebook analyzes the 2025 Stack Overflow Developer Survey dataset using Python and Pandas.
The analysis focuses on participant count, complete responses, work experience, remote work, Python usage, learning methods, compensation, education level, age groups, and industries.

In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("results.csv", low_memory=False)
df.head()

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0

In [5]:
df.shape

(49191, 172)

In [6]:
df.columns.tolist()

['ResponseId',
 'MainBranch',
 'Age',
 'EdLevel',
 'Employment',
 'EmploymentAddl',
 'WorkExp',
 'LearnCodeChoose',
 'LearnCode',
 'LearnCodeAI',
 'AILearnHow',
 'YearsCode',
 'DevType',
 'OrgSize',
 'ICorPM',
 'RemoteWork',
 'PurchaseInfluence',
 'TechEndorseIntro',
 'TechEndorse_1',
 'TechEndorse_2',
 'TechEndorse_3',
 'TechEndorse_4',
 'TechEndorse_5',
 'TechEndorse_6',
 'TechEndorse_7',
 'TechEndorse_8',
 'TechEndorse_9',
 'TechEndorse_13',
 'TechEndorse_13_TEXT',
 'TechOppose_1',
 'TechOppose_2',
 'TechOppose_3',
 'TechOppose_5',
 'TechOppose_7',
 'TechOppose_9',
 'TechOppose_11',
 'TechOppose_13',
 'TechOppose_16',
 'TechOppose_15',
 'TechOppose_15_TEXT',
 'Industry',
 'JobSatPoints_1',
 'JobSatPoints_2',
 'JobSatPoints_3',
 'JobSatPoints_4',
 'JobSatPoints_5',
 'JobSatPoints_6',
 'JobSatPoints_7',
 'JobSatPoints_8',
 'JobSatPoints_9',
 'JobSatPoints_10',
 'JobSatPoints_11',
 'JobSatPoints_13',
 'JobSatPoints_14',
 'JobSatPoints_15',
 'JobSatPoints_16',
 'JobSatPoints_15_TEXT',
 'AIThreat',
 'NewRole',
 'ToolCountWork',
 'ToolCountPersonal',
 'Country',
 'Currency',
 'CompTotal',
 'LanguageChoice',
 'LanguageHaveWorkedWith',
 'LanguageWantToWorkWith',
 'LanguageAdmired',
 'LanguagesHaveEntry',
 'LanguagesWantEntry',
 'DatabaseChoice',
 'DatabaseHaveWorkedWith',
 'DatabaseWantToWorkWith',
 'DatabaseAdmired',
 'DatabaseHaveEntry',
 'DatabaseWantEntry',
 'PlatformChoice',
 'PlatformHaveWorkedWith',
 'PlatformWantToWorkWith',
 'PlatformAdmired',
 'PlatformHaveEntry',
 'PlatformWantEntry',
 'WebframeChoice',
 'WebframeHaveWorkedWith',
 'WebframeWantToWorkWith',
 'WebframeAdmired',
 'WebframeHaveEntry',
 'WebframeWantEntry',
 'DevEnvsChoice',
 'DevEnvsHaveWorkedWith',
 'DevEnvsWantToWorkWith',
 'DevEnvsAdmired',
 'DevEnvHaveEntry',
 'DevEnvWantEntry',
 'SOTagsHaveWorkedWith',
 'SOTagsWantToWorkWith',
 'SOTagsAdmired',
 'SOTagsHaveEntry',
 'SOTagsWant Entry',
 'OpSysPersonal use',
 'OpSysProfessional use',
 'OfficeStackAsyncHaveWorkedWith',
 'OfficeStackAsyncWantToWorkWith',
 'OfficeStackAsyncAdmired',
 'OfficeStackHaveEntry',
 'OfficeStackWantEntry',
 'CommPlatformHaveWorkedWith',
 'CommPlatformWantToWorkWith',
 'CommPlatformAdmired',
 'CommPlatformHaveEntr',
 'CommPlatformWantEntr',
 'AIModelsChoice',
 'AIModelsHaveWorkedWith',
 'AIModelsWantToWorkWith',
 'AIModelsAdmired',
 'AIModelsHaveEntry',
 'AIModelsWantEntry',
 'SOAccount',
 'SOVisitFreq',
 'SODuration',
 'SOPartFreq',
 'SO_Dev_Content',
 'SO_Actions_1',
 'SO_Actions_16',
 'SO_Actions_3',
 'SO_Actions_4',
 'SO_Actions_5',
 'SO_Actions_6',
 'SO_Actions_9',
 'SO_Actions_7',
 'SO_Actions_10',
 'SO_Actions_15',
 'SO_Actions_15_TEXT',
 'SOComm',
 'SOFriction',
 'AISelect',
 'AISent',
 'AIAcc',
 'AIComplex',
 'AIToolCurrently partially AI',
 "AIToolDon't plan to use AI for this task",
 'AIToolPlan to partially use AI',
 'AIToolPlan to mostly use AI',
 'AIToolCurrently mostly AI',
 'AIFrustration',
 'AIExplain',
 'AIAgents',
 'AIAgentChange',
 'AIAgent_Uses',
 'AgentUsesGeneral',
 'AIAgentImpactSomewhat agree',
 'AIAgentImpactNeutral',
 'AIAgentImpactSomewhat disagree',
 'AIAgentImpactStrongly agree',
 'AIAgentImpactStrongly disagree',
 'AIAgentChallengesNeutral',
 'AIAgentChallengesSomewhat disagree',
 'AIAgentChallengesStrongly agree',
 'AIAgentChallengesSomewhat agree',
 'AIAgentChallengesStrongly disagree',
 'AIAgentKnowledge',
 'AIAgentKnowWrite',
 'AIAgentOrchestration',
 'AIAgentOrchWrite',
 'AIAgentObserveSecure',
 'AIAgentObsWrite',
 'AIAgentExternal',
 'AIAgentExtWrite',
 'AIHuman',
 'AIOpen',
 'ConvertedCompYearly',
 'JobSat']

## 1. How many people participated in the survey?

Each row in the dataset represents one survey respondent. Therefore, the total number of participants is equal to the number of rows in the dataset.

In [7]:
total_participants = df.shape[0]
total_participants

49191

In [8]:
participant_summary = pd.DataFrame({
    "Metric": ["Total Participants"],
    "Value": [df.shape[0]]
})

participant_summary

               Metric  Value
0  Total Participants  49191

## 2. How many participants answered all questions?

A complete response means that the participant has no missing values across all columns in the dataset.
Rows with no missing values were counted using `dropna()`.

In [9]:
complete_responses = df.dropna().shape[0]
complete_responses

0

In [10]:
complete_response_summary = pd.DataFrame({
    "Metric": ["Complete Responses"],
    "Value": [df.dropna().shape[0]]
})

complete_response_summary

               Metric  Value
0  Complete Responses      0

## 3. What are the central tendency measures for WorkExp?

The central tendency of participants' work experience was analyzed using mean, median, and mode.
Missing values were ignored during the calculation.

In [13]:
workexp_mean = df["WorkExp"].mean()
workexp_median = df["WorkExp"].median()
workexp_mode = df["WorkExp"].mode()[0]

workexp_mean, workexp_median, workexp_mode

(np.float64(13.367402606485907), 10.0, np.float64(10.0))

In [14]:
workexp_summary = pd.DataFrame({
    "Measure": ["Mean", "Median", "Mode"],
    "Value": [
        df["WorkExp"].mean(),
        df["WorkExp"].median(),
        df["WorkExp"].mode()[0]
    ]
})

workexp_summary

  Measure      Value
0    Mean  13.367403
1  Median  10.000000
2    Mode  10.000000

## 4. How many people work remotely?

The `RemoteWork` column was used to identify respondents who work remotely.
First, the distribution of all remote work categories was checked, then the number of remote workers was calculated.

In [15]:
df["RemoteWork"].value_counts(dropna=False)

RemoteWork
NaN                                                                             15411
Remote                                                                          10931
Hybrid (some remote, leans heavy to in-person)                                   6732
In-person                                                                        6042
Hybrid (some in-person, leans heavy to flexibility)                              5831
Your choice (very flexible, you can come in when you want or just as needed)     4244
Name: count, dtype: int64

In [16]:
remote_workers = df[df["RemoteWork"] == "Remote"].shape[0]
remote_workers

10931

In [17]:
remote_work_summary = pd.DataFrame({
    "Metric": ["Remote Workers"],
    "Value": [remote_workers]
})

remote_work_summary

           Metric  Value
0  Remote Workers  10931

## 5. What percentage of participants program with Python?

The `LanguageHaveWorkedWith` column was used to identify respondents who have worked with Python.
Rows containing `Python` in this column were counted and divided by the total number of participants.

In [18]:
python_users = df["LanguageHaveWorkedWith"].str.contains("Python", na=False)

python_percentage = python_users.mean() * 100
python_percentage

np.float64(37.53938728629221)

In [19]:
python_users = df["LanguageHaveWorkedWith"].str.contains("Python", na=False)

python_summary = pd.DataFrame({
    "Metric": ["Python Users", "Python Usage Percentage"],
    "Value": [
        python_users.sum(),
        round(python_users.mean() * 100, 2)
    ]
})

python_summary

                    Metric     Value
0             Python Users  18466.00
1  Python Usage Percentage     37.54

## 6. How many people learned programming through online courses?

The `LearnCode` column was used to identify respondents who learned programming through online courses or certifications.
Rows containing `Online Courses or Certification` were counted.

In [21]:
online_course_learners = df["LearnCode"].str.contains("Online Courses or Certification", na=False)

online_course_count = online_course_learners.sum()
online_course_count

np.int64(10973)

In [22]:
online_course_summary = pd.DataFrame({
    "Metric": ["Online Course Learners"],
    "Value": [online_course_count]
})

online_course_summary

                   Metric  Value
0  Online Course Learners  10973

## 7. What are the mean and median yearly compensation values by country among participants who program with Python?

Participants who have worked with Python were filtered using the `LanguageHaveWorkedWith` column.
Then, the data was grouped by country and the mean and median values of `ConvertedCompYearly` were calculated for each country.
Missing compensation values were ignored automatically during aggregation.

In [24]:
python_users_df = df[df["LanguageHaveWorkedWith"].str.contains("Python", na=False)]

python_users_df.head()

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0
7,8,I am a developer by profession,35-44 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Employed,Engaged in paid work (20-29 hours per week);Tr...,22.0,"Yes, I am not new to coding but am learning ne...",Books / Physical media;Technical documentation...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I want to learn best practices;When I wan...,"Innovation, system design",72000.0,6.0
8,9,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,"Caring for dependents (children, elderly, etc....",9.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70000.0,8.0
15,16,I am a developer by profession,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Student,Engaged in paid work (20-29 hours per week);En...,5.0,"Yes, I am new to coding or currently a student",Online Courses or Certification (includes all ...,"No, I learned something that was not related t...",...,Vertex AI;Agno;AutoGen (Microsoft);CrewAI;IBM ...,NaN,Galileo;Honeycomb;Metero;New Relic;opik;Snyk,NaN,ChatGPT;AgentGPT;Auto-GPT;Devin AI;Glean (Ente...,NaN,When I don’t trust AI’s answers;When I have et...,5,NaN,7.0
17,18,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,NaN,1.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I want to learn best practices;When I hav...,NaN,NaN,6.0

In [25]:
python_comp_by_country = (
    python_users_df
    .groupby("Country")["ConvertedCompYearly"]
    .agg(["mean", "median"])
    .reset_index()
)

python_comp_by_country

                                  Country           mean    median
0                             Afghanistan   22328.666667    1000.0
1                                 Albania   47217.600000   50000.0
2                                 Algeria   20187.285714    7088.0
3                                 Andorra  226103.500000  226103.5
4                                  Angola            NaN       NaN
..                                    ...            ...       ...
162  Venezuela, Bolivarian Republic of...    9908.647059    3000.0
163                              Viet Nam  218837.166667    8254.0
164                                 Yemen   32929.500000   23672.0
165                                Zambia    5424.250000    3206.0
166                              Zimbabwe   34000.000000   25500.0

[167 rows x 3 columns]

In [27]:
python_users_df = df[df["LanguageHaveWorkedWith"].str.contains("Python", na=False)]

python_comp_by_country = (
    python_users_df
    .groupby("Country")["ConvertedCompYearly"]
    .agg(
        Respondent_Count="count",
        Mean_Yearly_Compensation="mean",
        Median_Yearly_Compensation="median"
    )
    .reset_index()
)

python_comp_by_country["Mean_Yearly_Compensation"] = python_comp_by_country["Mean_Yearly_Compensation"].round(2)
python_comp_by_country["Median_Yearly_Compensation"] = python_comp_by_country["Median_Yearly_Compensation"].round(2)

python_comp_by_country_sorted = python_comp_by_country.sort_values(
    by="Median_Yearly_Compensation",
    ascending=False
)

python_comp_by_country_sorted

,Country,Respondent_Count,Mean_Yearly_Compensation,Median_Yearly_Compensation
112,Oman,2,390135.00,390135.0
3,Andorra,2,226103.50,226103.5
159,United States of America,3126,173298.59,150000.0
72,Israel,104,135828.37,142594.0
145,Switzerland,240,156456.60,142592.0
...,...,...,...,...
107,Niger,0,NaN,NaN
114,Palau,0,NaN,NaN
117,Papua New Guinea,0,NaN,NaN
132,Senegal,0,NaN,NaN
148,Tajikistan,0,NaN,NaN

In [28]:
python_comp_by_country = (
    python_users_df
    .groupby("Country")["ConvertedCompYearly"]
    .agg(["mean", "median"])
    .reset_index()
)

python_comp_by_country

                                  Country           mean    median
0                             Afghanistan   22328.666667    1000.0
1                                 Albania   47217.600000   50000.0
2                                 Algeria   20187.285714    7088.0
3                                 Andorra  226103.500000  226103.5
4                                  Angola            NaN       NaN
..                                    ...            ...       ...
162  Venezuela, Bolivarian Republic of...    9908.647059    3000.0
163                              Viet Nam  218837.166667    8254.0
164                                 Yemen   32929.500000   23672.0
165                                Zambia    5424.250000    3206.0
166                              Zimbabwe   34000.000000   25500.0

[167 rows x 3 columns]

## 8. What are the education levels of the top 5 participants with the highest compensation?

The dataset was sorted by `ConvertedCompYearly` in descending order.
The top 5 respondents with the highest yearly compensation were selected, and their education levels were displayed using the `EdLevel` column.

In [31]:
top_5_compensation = df.sort_values(
    by="ConvertedCompYearly",
    ascending=False
).head(5)

top_5_compensation[["ConvertedCompYearly", "EdLevel"]]

       ConvertedCompYearly                                          EdLevel
34267           50000000.0              Associate degree (A.A., A.S., etc.)
28700           33552715.0  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
43143           18387548.0              Associate degree (A.A., A.S., etc.)
35353           15430267.0     Bachelor’s degree (B.A., B.S., B.Eng., etc.)
45971           13921760.0  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)

In [32]:
top_5_education = (
    df.sort_values(by="ConvertedCompYearly", ascending=False)
    .head(5)[["ConvertedCompYearly", "EdLevel"]]
    .reset_index(drop=True)
)

top_5_education

   ConvertedCompYearly                                          EdLevel
0           50000000.0              Associate degree (A.A., A.S., etc.)
1           33552715.0  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
2           18387548.0              Associate degree (A.A., A.S., etc.)
3           15430267.0     Bachelor’s degree (B.A., B.S., B.Eng., etc.)
4           13921760.0  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)

## Bonus 1. What percentage of participants program with Python in each age group?

The `Age` column was used to group participants by age group.
For each age group, the percentage of respondents who have worked with Python was calculated using the `LanguageHaveWorkedWith` column.

In [33]:
df["UsesPython"] = df["LanguageHaveWorkedWith"].str.contains("Python", na=False)

df[["Age", "LanguageHaveWorkedWith", "UsesPython"]].head()

,Age,LanguageHaveWorkedWith,UsesPython
0,25-34 years old,Bash/Shell (all shells);Dart;SQL,False
1,25-34 years old,Java,False
2,35-44 years old,Dart;HTML/CSS;JavaScript;TypeScript,False
3,35-44 years old,Java;Kotlin;SQL,False
4,35-44 years old,C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...,True

In [34]:
python_by_age = (
    df.groupby("Age")["UsesPython"]
    .mean()
    .mul(100)
    .round(2)
    .reset_index()
)

python_by_age.columns = ["Age Group", "Python Usage Percentage"]

python_by_age

           Age Group  Python Usage Percentage
0    18-24 years old                    40.00
1    25-34 years old                    36.94
2    35-44 years old                    36.72
3    45-54 years old                    38.63
4    55-64 years old                    37.24
5  65 years or older                    31.63
6  Prefer not to say                    31.22

## Bonus 2. What are the most common industries among remote workers in the top 25% yearly compensation group?

The 75th percentile of `ConvertedCompYearly` was calculated to identify the top 25% compensation group.
Then, respondents who were both in this top compensation group and working remotely were filtered.
Finally, the most common industries were identified using the `Industry` column.

In [35]:
compensation_75th_percentile = df["ConvertedCompYearly"].quantile(0.75)
compensation_75th_percentile

np.float64(120596.0)

In [36]:
top_25_remote_workers = df[
    (df["ConvertedCompYearly"] >= compensation_75th_percentile) &
    (df["RemoteWork"] == "Remote")
]

top_25_remote_workers.head()

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat,UsesPython
29,30,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,Engaged in paid work (10-19 hours per week),19.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,Being able to make sure the AI code is correct...,205000.0,8.0,False
31,32,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,17.0,"No, I am not new to coding and did not learn n...",NaN,"No, I didn't spend time learning in the past year",...,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,NaN,250000.0,8.0,False
41,42,I am a developer by profession,45-54 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Transitioning to retirement (gradually reducin...,25.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,"Requirements gathering, big fixing",270000.0,3.0,True
42,43,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc....",25.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Microsoft C...,NaN,When I want to fully understand something;When...,Multiplatform Platform code conversion. Langua...,250000.0,8.0,True
48,49,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,15.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"Problem solving and reasoning, unless we get f...",142949.0,7.0,False

In [37]:
top_industries_table = (
    top_25_remote_workers["Industry"]
    .value_counts()
    .head(10)
    .reset_index()
)

top_industries_table.columns = ["Industry", "Count"]

top_industries_table

                                     Industry  Count
0                        Software Development   1186
1                                     Fintech    190
2                                  Healthcare    188
3                                      Other:    176
4  Internet, Telecomm or Information Services    138
5                  Banking/Financial Services     88
6                                  Government     78
7                Media & Advertising Services     75
8                Retail and Consumer Services     65
9             Transportation, or Supply Chain     63